# coding: utf-8

"""
    HPS Data Transfer Server API

    [WIP].  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.ops_operation import OpsOperation  # noqa: E501
from openapi_client.rest import ApiException

class TestOpsOperation(unittest.TestCase):
    """OpsOperation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OpsOperation
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpsOperation`
        """
        model = openapi_client.models.ops_operation.OpsOperation()  # noqa: E501
        if include_optional :
            return OpsOperation(
                children = [
                    ''
                    ], 
                description = '', 
                error = '', 
                id = '', 
                messages = [
                    ''
                    ], 
                progress = 1.337, 
                result = None, 
                state = 'unknown'
            )
        else :
            return OpsOperation(
        )
        """

    def testOpsOperation(self):
        """Test OpsOperation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
