# coding: utf-8

"""
    HPS Data Transfer Server API

    [WIP].  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openapi_client
from openapi_client.api.data_transfer_api import DataTransferApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDataTransferApi(unittest.TestCase):
    """DataTransferApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.data_transfer_api.DataTransferApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_data_remote_path_get(self):
        """Test case for data_remote_path_get

        Download a file  # noqa: E501
        """
        pass

    def test_data_remote_path_post(self):
        """Test case for data_remote_path_post

        Upload a file  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
