# coding: utf-8

"""
    HPS Data Transfer Server API

    [WIP].  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.rest_src_dst_operations import RestSrcDstOperations  # noqa: E501
from openapi_client.rest import ApiException

class TestRestSrcDstOperations(unittest.TestCase):
    """RestSrcDstOperations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RestSrcDstOperations
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestSrcDstOperations`
        """
        model = openapi_client.models.rest_src_dst_operations.RestSrcDstOperations()  # noqa: E501
        if include_optional :
            return RestSrcDstOperations(
                operations = [
                    openapi_client.models.rest/src_dst.rest.SrcDst(
                        dst = openapi_client.models.rest/storage_path.rest.StoragePath(
                            path = 'my/path/to/data', 
                            remote = 'any', ), 
                        src = openapi_client.models.rest/storage_path.rest.StoragePath(
                            path = 'my/path/to/data', 
                            remote = 'any', ), )
                    ]
            )
        else :
            return RestSrcDstOperations(
                operations = [
                    openapi_client.models.rest/src_dst.rest.SrcDst(
                        dst = openapi_client.models.rest/storage_path.rest.StoragePath(
                            path = 'my/path/to/data', 
                            remote = 'any', ), 
                        src = openapi_client.models.rest/storage_path.rest.StoragePath(
                            path = 'my/path/to/data', 
                            remote = 'any', ), )
                    ],
        )
        """

    def testRestSrcDstOperations(self):
        """Test RestSrcDstOperations"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
