# coding: utf-8

"""
    HPS Data Transfer Server API

    [WIP].  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openapi_client
from openapi_client.api.storage_api import StorageApi  # noqa: E501
from openapi_client.rest import ApiException


class TestStorageApi(unittest.TestCase):
    """StorageApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.storage_api.StorageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_storage_get(self):
        """Test case for storage_get

        Get storage configuration  # noqa: E501
        """
        pass

    def test_storagecopy_post(self):
        """Test case for storagecopy_post

        Copy data  # noqa: E501
        """
        pass

    def test_storageexists_post(self):
        """Test case for storageexists_post

        Check existence of files and directories  # noqa: E501
        """
        pass

    def test_storagelist_post(self):
        """Test case for storagelist_post

        List a directory  # noqa: E501
        """
        pass

    def test_storagemkdir_post(self):
        """Test case for storagemkdir_post

        Create a directory  # noqa: E501
        """
        pass

    def test_storagemove_post(self):
        """Test case for storagemove_post

        Move files and directories  # noqa: E501
        """
        pass

    def test_storageremove_post(self):
        """Test case for storageremove_post

        Remove files  # noqa: E501
        """
        pass

    def test_storagermdir_post(self):
        """Test case for storagermdir_post

        Remove a directory  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
