# coding: utf-8

"""
    HPS Data Transfer Server API

    [WIP].  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openapi_client
from openapi_client.api.operations_api import OperationsApi  # noqa: E501
from openapi_client.rest import ApiException


class TestOperationsApi(unittest.TestCase):
    """OperationsApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.operations_api.OperationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_operations_get(self):
        """Test case for operations_get

        Get operations  # noqa: E501
        """
        pass

    def test_operationsbatch_post(self):
        """Test case for operationsbatch_post

        Get operations  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
