# coding: utf-8

"""
    HPS Data Transfer Server API

    [WIP].  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.rest_status import RestStatus  # noqa: E501
from openapi_client.rest import ApiException

class TestRestStatus(unittest.TestCase):
    """RestStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test RestStatus
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RestStatus`
        """
        model = openapi_client.models.rest_status.RestStatus()  # noqa: E501
        if include_optional :
            return RestStatus(
                build_info = openapi_client.models.rest/build_info.rest.buildInfo(
                    branch = '', 
                    mode = '', 
                    revision = '', 
                    short_revision = '', 
                    version = '', ), 
                time = ''
            )
        else :
            return RestStatus(
        )
        """

    def testRestStatus(self):
        """Test RestStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
