# coding: utf-8

"""
    HPS Data Transfer Server API

    [WIP].  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest

import openapi_client
from openapi_client.api.tokens_api import TokensApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTokensApi(unittest.TestCase):
    """TokensApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.tokens_api.TokensApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_remotes_remote_tokens_post(self):
        """Test case for remotes_remote_tokens_post

        Create Tokens  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
