# coding: utf-8

"""
    HPS Data Transfer Server API

    [WIP].  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openapi_client
from openapi_client.models.ops_operation_state import OpsOperationState  # noqa: E501
from openapi_client.rest import ApiException

class TestOpsOperationState(unittest.TestCase):
    """OpsOperationState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOpsOperationState(self):
        """Test OpsOperationState"""
        # inst = OpsOperationState()

if __name__ == '__main__':
    unittest.main()
