# generated by datamodel-codegen

from __future__ import annotations

from pydantic import BaseModel, Field


class FieldDataRemotePathPostRequest(BaseModel):
    file: bytes = Field(..., description='File')
