# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2024-07-19T08:19:49+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class UserInfo(BaseModel):
    groups: Optional[List[str]] = None
    id: Optional[str] = None
    is_admin: Optional[bool] = None
    roles: Optional[List[str]] = None
    username: Optional[str] = None
