# generated by datamodel-codegen

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class ErrorResponse(BaseModel):
    error: Optional[str] = 'something bad happened'
