# generated by datamodel-codegen

from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import BaseModel, RootModel


class DataAssignment(BaseModel):
    custom: Optional[Dict[str, Any]] = None


class DataAssignments(RootModel[Optional[Dict[str, DataAssignment]]]):
    root: Optional[Dict[str, DataAssignment]] = None


class SrcDst(BaseModel):
    dst: str
    src: str
