# generated by datamodel-codegen

from __future__ import annotations

from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel


class OperationState(Enum):
    Unknown = "unknown"
    Queued = "queued"
    Running = "running"
    Succeeded = "succeeded"
    Failed = "failed"


class Operation(BaseModel):
    children: Optional[List[str]] = None
    description: Optional[str] = None
    ended_at: Optional[str] = None
    error: Optional[str] = None
    id: Optional[str] = None
    messages: Optional[List[str]] = None
    progress: Optional[float] = None
    queued_at: Optional[str] = None
    remotes: Optional[List[str]] = None
    result: Optional[Any] = None
    started_at: Optional[str] = None
    state: Optional[OperationState] = None
