# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2024-07-19T08:19:49+00:00

from __future__ import annotations

from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class OperationState(Enum):
    Unknown = 'unknown'
    Queued = 'queued'
    Running = 'running'
    Succeeded = 'succeeded'
    Failed = 'failed'


class Operation(BaseModel):
    children: Optional[List[str]] = None
    description: Optional[str] = None
    error: Optional[str] = None
    id: Optional[str] = None
    messages: Optional[List[str]] = None
    progress: Optional[float] = None
    result: Optional[Dict[str, Any]] = None
    state: Optional[OperationState] = None
