# generated by datamodel-codegen

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from . import storage


class TokenResponse(BaseModel):
    pass


class TokenRequest(BaseModel):
    other: Optional[Dict[str, Any]] = Field(None, description="For custom use")
    read: Optional[List[str]] = None
    recursive: Optional[bool] = None
    type: Optional[storage.PathType] = None
    write: Optional[List[str]] = None
