version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    insecure-external-code-execution: allow
    schedule:
      interval: "daily"
    labels:
      - "maintenance"
      - "dependencies"
    groups:
      general-dependencies:
        patterns:
          - "*"
        exclude-patterns:
          - "*sphinx*"
          - "pytest*"
      test-dependencies:
        patterns:
          - "pytest*"
      doc-dependencies:
        patterns:
          - "*sphinx*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "maintenance"
