repos:

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.2
  hooks:
    - id: ruff
      args: [--fix]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    exclude: >
      (?x)^(
          .*\.dat|
          .*\.mac|
          .*\.k|
          .*\.cas
      )$
    args: ["--ignore-words", "doc/styles/config/vocabularies/ANSYS/accept.txt"]

# For now we disable some of these checks, can be reenabled later
# - repo: https://github.com/pycqa/pydocstyle
#   rev: 6.3.0
#   hooks:
#  - id: pydocstyle
#    additional_dependencies: [toml]
#    exclude: "tests/"

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: trailing-whitespace

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.29.1
  hooks:
    - id: check-github-workflows

- repo: https://github.com/ansys/pre-commit-hooks
  rev: v0.4.3
  hooks:
  - id: add-license-headers
