#!/bin/bash


docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
    -i /local/openapi2.json \
    -g openapi \
    -o /local/out --skip-validate-spec

poetry run datamodel-codegen --input ./out/openapi.json --input-file-type openapi --output ansys/hps/data_transfer/client/models --output-model-type pydantic_v2.BaseModel --custom-file-header "# generated by datamodel-codegen"

sed_cmd=sed

if [ "$(uname)" == "Darwin" ]; then
    sed_cmd=gsed
fi

pushd ansys/hps/data_transfer/client/models
$sed_cmd -i 's/from \. import ops, permissions/from \. import ops, permissions as perms #noqa: F401/g' msg.py
$sed_cmd -i 's/permissions\./perms\./g' msg.py
$sed_cmd -i 's/result: Optional\[Dict\[str, Any\]\] = None/result: Optional\[Any\] = None/g' ops.py
popd

# black ansys/hps/data_transfer/client/models
# dev_env/bin/python -m pip install autoflake
# dev_env/bin/autoflake --recursive --ignore-init-module-imports --remove-all-unused-imports --in-place ansys/hps/data_transfer/client/models
for i in {1..10}
do
    echo "Running $i iteration"
    poetry run pre-commit run --all-files
    if [ $? -eq 0 ]
    then
        break
    fi
done
