# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2024-06-03T17:37:06+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel


class Operation(BaseModel):
    children: Optional[List[str]] = None
    description: Optional[str] = None
    error: Optional[str] = None
    id: Optional[str] = None
    messages: Optional[List[str]] = None
    progress: Optional[float] = None
    result: Optional[Dict[str, Any]] = None
    state: Optional[str] = None
