# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2024-06-05T13:02:34+00:00

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class TokenRequest(BaseModel):
    other: Optional[Dict[str, Any]] = Field(None, description="For custom use")
    read: Optional[List[str]] = None
    write: Optional[List[str]] = None


class TokenResponse(BaseModel):
    pass
