# generated by datamodel-codegen

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel


class UserInfo(BaseModel):
    groups: Optional[List[str]] = None
    id: Optional[str] = None
    is_admin: Optional[bool] = None
    roles: Optional[List[str]] = None
    username: Optional[str] = None
