# Copyright (C) 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# generated by datamodel-codegen

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import AnyUrl, AwareDatetime, BaseModel, ConfigDict, Field, conint


class AuthRedirectRequestBody(BaseModel):
    pass
    model_config = ConfigDict(
        extra="forbid",
    )


class AuthTokenResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    token: str


class BinaryInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    platform: str
    size: int
    type: str


class BuildInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    architecture: str | None = None
    branch: str | None = None
    go_version: str | None = None
    mode: str | None = None
    operating_system: str | None = None
    revision: str | None = None
    short_revision: str | None = None
    timestamp: str | None = None
    version: str | None = None
    version_hash: str | None = None


class CheckPermissionsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    allowed: bool = Field(..., description="Indicates if the check was successful")


class CompatBackend(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    obj_type: str
    priority: int
    reference: str
    url: str
    use_default_url: bool


class CompatBuildInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    branch: str
    revision: str
    short_revision: str
    timestamp: str
    version: str


class CompatCopyRequestBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    destination: str


class CompatCopyResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    checksum: str


class CompatHealthResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ansft: bool
    build: CompatBuildInfo


class CompatStorageResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    backends: list[CompatBackend] | None


class CompatUploadResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    checksum: str


class DataAssignment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    compressed_size: conint(ge=0) | None = None
    compression: str | None = None
    custom: dict[str, Any] | None = None
    uncompressed_size: conint(ge=0) | None = None


class ErrorDetail(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    location: str | None = Field(
        None,
        description="Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'",
    )
    message: str | None = Field(None, description="Error message text")
    value: Any | None = Field(None, description="The value at the given location")


class ErrorModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    detail: str | None = Field(
        None,
        description="A human-readable explanation specific to this occurrence of the problem.",
        examples=["Property foo is required but is missing."],
    )
    errors: list[ErrorDetail] | None = Field(None, description="Optional list of individual error details")
    instance: AnyUrl | None = Field(
        None,
        description="A URI reference that identifies the specific occurrence of the problem.",
        examples=["https://example.com/error-log/abc123"],
    )
    status: int | None = Field(None, description="HTTP status code", examples=[400])
    title: str | None = Field(
        None,
        description="A short, human-readable summary of the problem type. This value should not change between occurrences of the error.",
        examples=["Bad Request"],
    )
    type: AnyUrl | None = Field(
        "about:blank",
        description="A URI reference to human-readable documentation for the error.",
        examples=["https://example.com/errors/example"],
    )


class Features(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    auth_types: list[str] | None = None
    compression_plugins: list[str] | None = None
    metadata_plugins: list[str] | None = None
    operation_plugins: list[str] | None = None
    permissions_plugins: list[str] | None = None
    storage_plugins: list[str] | None = None


class FileDownloadTokenResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    token: str


class ListBinariesResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    available: list[BinaryInfo] | None


class State(Enum):
    unknown = "unknown"
    queued = "queued"
    running = "running"
    succeeded = "succeeded"
    failed = "failed"


class Operation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    children: list[str] | None
    children_detail: list[Operation] | None = None
    description: str
    ended_at: AwareDatetime
    error: str
    id: str
    info: dict[str, Any] | None = None
    messages: list[str] | None
    progress: float
    progress_current: conint(ge=0)
    progress_total: conint(ge=0)
    queued_at: AwareDatetime
    rate: str
    result: Any
    started_at: AwareDatetime
    state: State
    succeeded_on: list[str] | None
    user_id: str


class OperationIdResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., description="ID of the operation", examples=["2diK2kCkpgeHAQSNthIZ1JYyPte"])
    location: str = Field(
        ...,
        description="Location to poll for operation status, provided in the body for convenience",
        examples=["/api/v1/operations/2diK2kCkpgeHAQSNthIZ1JYyPte"],
    )


class OperationsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    ids: list[str] | None = Field(..., description="List of operation IDs to retrieve")


class OperationsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operations: list[Operation] | None


class PlainSrcDst(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dst: str
    src: str


class RemoveMetadataRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    paths: list[str] | None = Field(..., description="Paths to remove metadata for")
    recursive: bool = Field(..., description="Whether to remove metadata recursively")


class Resource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str = Field(..., examples=["my/path/to/data/file.txt"])
    type: str = Field(..., examples=["document"])


class SetMetadataRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    metadata: dict[str, DataAssignment] = Field(..., description="Per-path metadata to set")


class StatusResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    build_info: BuildInfo | None = Field(None, description="Information about the build")
    features: Features | None = Field(None, description="List of features and plugins available in the server")
    ready: bool | None = Field(None, description="Indicates if the server is ready to accept requests")
    time: str | None = Field(None, description="Current server time")


class StorageConfigResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    storage: list[Any] | None = None


class StoragePath(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str
    remote: str = "any"


class Subject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., examples=["946991ec-828c-4de4-acbe-962ada8bc441"])
    type: str = Field(..., examples=["user"])


class TokenRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    other: dict[str, Any] | None = None
    read: list[str] | None
    recursive: bool
    type: str
    write: list[str] | None


class UserCredentials(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    password: str


class UserInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    account_id: str
    groups: list[str] | None
    id: str
    is_admin: bool
    roles: list[str] | None
    service_admin: bool
    username: str


class WhoamiResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    user: UserInfo


class WorkerConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    auth: dict[str, Any] | None = None
    compression: dict[str, Any] | None = None
    metadata: dict[str, Any] | None = None
    permissions: dict[str, Any] | None = None
    storage: list[Any] | None = None
    user_id: str | None = None


class WorkerResetResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: str


class WorkerTokenResponseBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expires_at: AwareDatetime
    token: str


class AuthTokenRequestBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    credentials: UserCredentials


class CopyMetadataRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    recursive: bool = Field(..., description="Whether to copy metadata recursively")
    src_dst: list[PlainSrcDst] | None = Field(..., description="Sources and destinations for the copy")


class GetMetadataRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operations: list[StoragePath] | None = Field(None, description="Deprecated as of 2024.09.10")
    paths: list[str] | None = Field(None, description="Paths to retrieve metadata for")


class MoveMetadataRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    recursive: bool = Field(..., description="Whether to move metadata recursively")
    src_dst: list[PlainSrcDst] | None = Field(..., description="Sources and destinations for the move")


class PathOperations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operations: list[StoragePath] | None


class RoleAssignment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource: Resource
    role: str = Field(..., examples=["reader"])
    subject: Subject


class RoleQuery(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    resource: Resource
    role: str | None = Field(None, examples=["reader"])
    subject: Subject


class SetPermissionsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permissions: list[RoleAssignment] | None = Field(..., description="Permission definitions to set")


class SrcDst(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    dst: StoragePath
    src: StoragePath


class SrcDstOperations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operations: list[SrcDst] | None


class CheckPermissionsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permissions: list[RoleAssignment] | None = Field(..., description="Permission to check for")


class GetPermissionsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permissions: list[RoleQuery] | None = Field(..., description="Permission query to perform")


class GetPermissionsResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permissions: list[RoleAssignment] | None = Field(..., description="Permissions retrieved from the system")


class RemovePermissionsRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    permissions: list[RoleAssignment] | None = Field(..., description="Permission to remove")


Operation.model_rebuild()
