# Copyright (C) 2022 - 2025 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: MIT
#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# generated by datamodel-codegen
"""Module providing BuildInfo schema and a other data transfer operation Response schemas."""

from __future__ import annotations

from typing import Any, Dict, List, Optional

from pydantic import BaseModel

from . import metadata, ops


class BuildInfo(BaseModel):
    branch: str | None = None
    mode: str | None = None
    revision: str | None = None
    short_revision: str | None = None
    timestamp: str | None = None
    version: str | None = None
    version_hash: str | None = None


class CheckPermissionsResponse(BaseModel):
    allowed: bool | None = None


class CopyMetadataRequest(BaseModel):
    recursive: bool | None = None
    src_dst: list[metadata.SrcDst]


class FileDownloadTokenResponse(BaseModel):
    token: str | None = None


class GetMetadataRequest(BaseModel):
    paths: list[str] | None = None


class MetadataConfigResponse(BaseModel):
    config: dict[str, Any] | None = None


class MoveMetadataRequest(BaseModel):
    recursive: bool | None = None
    src_dst: list[metadata.SrcDst]


class OpIdResponse(BaseModel):
    id: str | None = "2diK2kCkpgeHAQSNthIZ1JYyPte"
    location: str | None = "/api/v1/operations/2diK2kCkpgeHAQSNthIZ1JYyPte"


class OpsRequest(BaseModel):
    ids: list[str]


class PermissionsConfigResponse(BaseModel):
    config: dict[str, Any] | None = None


class RemoveMetadataRequest(BaseModel):
    paths: list[str]
    recursive: bool | None = None


class SetMetadataRequest(BaseModel):
    metadata: metadata.DataAssignments


class Status(BaseModel):
    build_info: BuildInfo | None = None
    ready: bool | None = None
    time: str | None = None


class StorageConfigResponse(BaseModel):
    storage: list[dict[str, Any]] | None = None


class StoragePath(BaseModel):
    path: str
    remote: str | None = "any"


class PathOperations(BaseModel):
    operations: list[StoragePath]


class SrcDst(BaseModel):
    dst: StoragePath
    src: StoragePath


class SrcDstOperations(BaseModel):
    operations: list[SrcDst]


class OpsResponse(BaseModel):
    operations: list[ops.Operation] | None = None


class CheckPermissionsRequest(BaseModel):
    permissions: list[perms.RoleAssignment] | None = None


class GetPermissionsRequest(BaseModel):
    permissions: list[perms.RoleQuery] | None = None


class GetPermissionsResponse(BaseModel):
    permissions: list[perms.RoleAssignment] | None = None


class RemovePermissionsRequest(BaseModel):
    permissions: list[perms.RoleAssignment] | None = None


class SetPermissionsRequest(BaseModel):
    permissions: list[perms.RoleAssignment] | None = None
