name: 🐞 Bug
description: Fill a bug report here
title: "Bug located in ..."
labels: ["bug"]
assignees: [""]

body:
  - type: textarea
    id: bug-description
    attributes:
      label: '🐞 Description of the bug'
      placeholder: Describe what bug you encountered and what should have happened.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: '📝 Steps to reproduce'
      placeholder: Please write the steps to reproduce the issue.
    validations:
      required: true

  - type: textarea
    id: installed-packages
    attributes:
      label: Installed packages
      description: Run `python -m pip freeze` to list installed packages
      placeholder: Paste the output of `python -m pip freeze` here
    validations:
      required: true


