name: 💡 New feature
description: features should define complete functionality that is testable and capable of adding value for the customer when shipped
title: "Add ..."
labels: ["feature"]
assignees: [""]

body:

  - type: textarea
    id: feature-description
    attributes:
      label: '📝 Description of the feature'
      placeholder: Describe the feature and why it is useful for the project
    validations:
      required: true

  - type: textarea
    id: acceptanceCriteria
    attributes:
      label: Acceptance Criteria
      description: List the criteria that must be met for the story to be considered complete.
      placeholder: "- Given [context], when [action], then [outcome]"
    validations:
      required: true

  - type: textarea
    id: business-value
    attributes:
      label: '💵 Business Value'
    validations:
      required: false

  - type: textarea
    id: references
    attributes:
      label: '🔗 Useful links and references'
    validations:
      required: false
