#!/bin/bash

models_dir=src/ansys/hps/data_transfer/client/models

curl --insecure -L https://localhost:8443/hps/dt/swagger/doc.json -o openapi2.json

docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
    -i /local/openapi2.json \
    -g openapi \
    -o /local/out --skip-validate-spec

datamodel-codegen --input ./out/openapi.json --input-file-type openapi --output $models_dir --output-model-type pydantic_v2.BaseModel --custom-file-header "# generated by datamodel-codegen"

sed_cmd=sed

if [ "$(uname)" == "Darwin" ]; then
    sed_cmd=gsed
fi

pushd $models_dir
# $sed_cmd -i 's/from \. import \(.*\) permissions\(.*\)/from \. import \1 permissions as perms\2 #noqa: F401/g' msg.py
# $sed_cmd -i 's/permissions\./perms\./g' msg.py
$sed_cmd -i 's/result: Optional\[Dict\[str, Any\]\] = None/result: Optional\[Any\] = None/g' ops.py
# $sed_cmd -i '/# generated by .*/a\from typing import Any' ops.py
$sed_cmd -i 's/ as Any_aliased//g' ops.py
$sed_cmd -i 's/class DataAssignments(\(.*\)):/class DataAssignments(\1): #noqa: UP007/g' metadata.py
popd

for i in {1..5}
do
    echo "Running $i iteration"
    pre-commit run --all-files
    if [ $? -eq 0 ]
    then
        break
    fi
done
