#!/bin/bash

set -e

models_dir=src/ansys/hps/data_transfer/client/models
url=https://localhost:8443/hps/dt/openapi.json

curl --insecure -L https://localhost:8443/hps/dt/openapi.json -o openapi.json

# docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
#     -i /local/openapi2.json \
#     -g openapi \
    # -o /local/out --skip-validate-spec

format_args="--use-default-kwarg --use-exact-imports"
# datamodel-codegen --url $url --http-ignore-tls --input-file-type auto --output $models_dir/models.py --output-model-type pydantic_v2.BaseModel --custom-file-header "# generated by datamodel-codegen" $extra_args
datamodel-codegen --input openapi.json --http-ignore-tls --input-file-type auto --output $models_dir/models.py --output-model-type pydantic_v2.BaseModel --custom-file-header "# generated by datamodel-codegen" $extra_args

sed_cmd=sed

if [ "$(uname)" == "Darwin" ]; then
    sed_cmd=gsed
fi


pushd $models_dir
$sed_cmd -i 's/remote: str/remote: str = "any"/' models.py
popd

for i in {1..5}
do
    echo "Running $i iteration"
    pre-commit run --all-files
    if [ $? -eq 0 ]
    then
        break
    fi
done
