# coding: utf-8

"""
    HPS Data Transfer Server API

    [WIP].  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr
from openapi_client.models.rest_build_info import RestBuildInfo

class RestStatus(BaseModel):
    """
    RestStatus
    """
    build_info: Optional[RestBuildInfo] = None
    time: Optional[StrictStr] = None
    __properties = ["build_info", "time"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RestStatus:
        """Create an instance of RestStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of build_info
        if self.build_info:
            _dict['build_info'] = self.build_info.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RestStatus:
        """Create an instance of RestStatus from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return RestStatus.parse_obj(obj)

        _obj = RestStatus.parse_obj({
            "build_info": RestBuildInfo.from_dict(obj.get("build_info")) if obj.get("build_info") is not None else None,
            "time": obj.get("time")
        })
        return _obj

