# coding: utf-8

"""
    HPS Data Transfer Server API

    [WIP].  # noqa: E501

    The version of the OpenAPI document: 1.0
    Contact: support@swagger.io
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class RestOpIdResponse(BaseModel):
    """
    RestOpIdResponse
    """
    id: Optional[StrictStr] = '2diK2kCkpgeHAQSNthIZ1JYyPte'
    location: Optional[StrictStr] = '/api/v1/operations/2diK2kCkpgeHAQSNthIZ1JYyPte'
    __properties = ["id", "location"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RestOpIdResponse:
        """Create an instance of RestOpIdResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RestOpIdResponse:
        """Create an instance of RestOpIdResponse from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return RestOpIdResponse.parse_obj(obj)

        _obj = RestOpIdResponse.parse_obj({
            "id": obj.get("id") if obj.get("id") is not None else '2diK2kCkpgeHAQSNthIZ1JYyPte',
            "location": obj.get("location") if obj.get("location") is not None else '/api/v1/operations/2diK2kCkpgeHAQSNthIZ1JYyPte'
        })
        return _obj

